export const userBillType = 'commonReducer/userBillType'
export const routers = 'commonReducer/routers'
export const breadcrumbList = 'commonReducer/breadcrumbList'
export const courseInfo = 'commonReducer/courseInfo'
export const searchCourseInfo = 'commonReducer/searchCourseInfo'
export const courseSection = 'commonReducer/courseSection'
